import { PITCH_INFO, type Pitch, type SongPitch } from './pitch'

export const COPY = {
  sv: {
    home: 'Note Nest startsida',
    progress: 'Lektionsframsteg',
    streak: (n: number) => `${n} rätta svar i rad`,
    sections: 'Lektionsdelar',
    learn: 'Lär dig en ton',
    quiz: 'Snabbquiz',
    practice: 'Spela med mikrofon',
    song: 'Låtar',
    chooseSong: 'Välj en låt att öva på',
    lesson: 'LEKTION 01 · DISKANTKLAVEN',
    practiceLesson: (step: number, total: number) => `GUIDAD ÖVNING · STEG ${step} AV ${total}`,
    songLesson: (title: string, step: number, total: number) => `${title.toUpperCase()} · NOT ${step} AV ${total}`,
    meet: 'Möt dina ',
    note: 'tonvänner.',
    practiceLead: 'Låt mobilen lyssna medan du spelar samma ton på ett riktigt piano nära mikrofonen.',
    songTitle: (title: string) => `Spela ${title}`,
    songLead: 'Följ noterna en i taget. Appen lyssnar och går vidare när du spelar rätt ton.',
    lessonIntro: 'Lär dig hitta tonerna C4–C5 på diskantklavens notlinjer och pianot.',
    every: 'Varje ton har ett namn',
    seven: 'Vi börjar med åtta toner från C4 till C5: ',
    repeat: 'De följer varandra steg för steg!',
    names: 'Tonerna C4 till C5',
    choose: (n: Pitch) => `Välj tonen ${n}`,
    spot: 'Hitta den på notlinjerna',
    map: 'Diskantklavens fem linjer är en musikalisk karta. C4 är mitt-C på en hjälplinje under notlinjerna.',
    play: 'Spela den på pianot',
    tap: 'Tryck på rätt tangent. Varje ton har sin egen frekvens och röst.',
    blackKey: (n: string) => `Spela ${n}`,
    ready: 'Jag är redo för quiz',
    keyboard: 'Pianoklaviatur från C4 till C5',
    middleC: 'mitt-C',
    quizScope: 'Quizet använder bara vita tangenter (C4–C5).',
    playNote: (n: Pitch) => n === 'C4' ? 'Spela C4, mitt-C' : `Spela ${n}`,
    staff: (n: SongPitch) => `Diskantklav med tonen ${n}`,
    titleStaff: (n: SongPitch) => `Diskantklav med tonen ${n}`,
    thisNote: (n: Pitch) => <>Den här tonen är <strong>{n}</strong>{n === 'C4' ? ' – mitt-C.' : '.'} {PITCH_INFO[n].hint.sv}</>,
    round: (n: number) => `SNABBQUIZ · RUNDA ${n}`,
    which: 'Vilken ton är <em>det här</em>?',
    read: 'Läs diskantklaven och tryck sedan på motsvarande tangent.',
    answer: 'Tryck på ditt svar',
    almost: (n: Pitch) => <>Nästan! Du tryckte på <strong>{n}</strong>. Läs noten och försök igen.</>,
    another: 'Försök igen',
    microphoneTitle: 'Lyssna på ditt riktiga piano',
    microphoneIntro: 'Appen jämför tonen den hör med noten på skärmen och går bara vidare när du spelar rätt.',
    microphoneButton: 'Starta mikrofon',
    microphoneStop: 'Stoppa mikrofon',
    microphoneWaiting: 'Väntar på mikrofonbehörighet…',
    microphoneReady: 'Mikrofonen lyssnar. Spela tonen på ditt piano.',
    microphoneIdle: 'Starta mikrofonen och spela tonen nära enheten.',
    microphoneUnsupported: 'Den här webbläsaren saknar mikrofonstöd för notigenkänning.',
    microphoneDenied: 'Mikrofonbehörighet nekades. Tillåt mikrofonen och försök igen.',
    microphoneError: 'Kunde inte starta mikrofonlyssning just nu.',
    microphoneCompleted: 'Mikrofonövningen är klar.',
    target: (n: SongPitch) => `Spela ${n} på ditt riktiga piano`,
    detected: 'Hörd ton',
    detectedNone: 'Ingen stabil ton ännu',
    detectedCorrect: 'Rätt ton — vi går vidare!',
    detectedWrong: 'Inte rätt ton ännu — försök igen.',
    completed: '🎉 Du klarade hela mikrofonövningen!',
    restartPractice: 'Börja om övningen',
    songIntro: 'Spela melodin på ditt riktiga piano. Börja med tonen som visas på notlinjerna.',
    songTarget: (n: SongPitch) => `Spela nästa ton: ${n}`,
    songCompleted: (title: string) => `🎉 Du spelade hela ${title}!`,
    restartSong: 'Börja om låten',
    debug: 'Felsökning',
    debugEyebrow: 'FELSÖKNINGSLÄGE · TONIGENKÄNNING',
    debugTitle: 'Se hur appen hör din ton',
    debugLead: 'Spela en ton på ditt riktiga piano nära mikrofonen. Ingen övning att klara — bara ren analys av vad appen hör och varför.',
    debugIntro: 'Starta mikrofonen och spela valfri tangent. Resultatet uppdateras löpande, ton för ton.',
    debugIdle: 'Starta mikrofonen och spela en ton.',
    debugWaiting: 'Lyssnar … spela en ton på pianot.',
    debugNote: 'Hörd ton',
    debugFrequencyLabel: 'Uppmätt frekvens',
    debugConfidenceLabel: 'Tydlighet',
    debugLevelLabel: 'Ljudnivå (RMS)',
    debugReason: (label: string, hz: string, pct: number, rms: string) => `Appen känner igen ${label} eftersom ljudvågen upprepar sig med ett mönster som motsvarar ${hz} Hz. En YIN-baserad periodicitetsanalys (CMNDF) hittade den bästa matchningen med ${pct}% tydlighet, och ljudnivån (RMS ${rms}) var stark nog för att lita på mätningen.`,
    debugUnstable: (hz: string, pct: number) => `Precis nu är signalen för svag eller otydlig för en säker tonbestämning (frekvens ${hz} Hz, tydlighet bara ${pct}%).`,
    footer: <>Gjord för nyfikna öron <span>·</span> Inga fel toner här 🎵</>,
    version: (version: string) => `Version ${version}`,
    language: 'Språk',
    swedish: 'Svenska',
    english: 'English',
    switchTo: (l: string) => `Byt språk till ${l}`,
  },
  en: {
    home: 'Note Nest home',
    progress: 'Lesson progress',
    streak: (n: number) => `${n} correct answers in a row`,
    sections: 'Lesson sections',
    learn: 'Learn a pitch',
    quiz: 'Quick quiz',
    practice: 'Play with microphone',
    song: 'Songs',
    chooseSong: 'Choose a song to practice',
    lesson: 'LESSON 01 · TREBLE CLEF',
    practiceLesson: (step: number, total: number) => `GUIDED PRACTICE · STEP ${step} OF ${total}`,
    songLesson: (title: string, step: number, total: number) => `${title.toUpperCase()} · NOTE ${step} OF ${total}`,
    meet: 'Meet your ',
    note: 'pitch friends.',
    practiceLead: 'Let the device listen while you play the same pitch on a real piano near the microphone.',
    songTitle: (title: string) => `Play ${title}`,
    songLead: 'Follow the notes one at a time. The app listens and moves on when you play the right pitch.',
    lessonIntro: 'Learn to find pitches C4–C5 on the treble staff and piano.',
    every: 'Every pitch has a name',
    seven: 'We start with eight pitches from C4 to C5: ',
    repeat: 'They move up one step at a time!',
    names: 'Pitches C4 to C5',
    choose: (n: Pitch) => `Choose pitch ${n}`,
    spot: 'Spot it on the staff',
    map: 'The five treble-clef lines are a musical map. C4 is middle C on a ledger line below the staff.',
    play: 'Play it on the piano',
    tap: 'Tap the matching key. Every pitch has its own frequency and voice.',
    blackKey: (n: string) => `Play ${n}`,
    ready: 'I’m ready for a quiz',
    keyboard: 'Piano keyboard from C4 to C5',
    middleC: 'middle C',
    quizScope: 'The quiz uses white keys only (C4–C5).',
    playNote: (n: Pitch) => n === 'C4' ? 'Play C4, middle C' : `Play ${n}`,
    staff: (n: SongPitch) => `Treble staff showing pitch ${n}`,
    titleStaff: (n: SongPitch) => `Treble staff with pitch ${n}`,
    thisNote: (n: Pitch) => <>This pitch is <strong>{n}</strong>{n === 'C4' ? ' — middle C.' : '.'} {PITCH_INFO[n].hint.en}</>,
    round: (n: number) => `QUICK QUIZ · ROUND ${n}`,
    which: 'Which pitch is <em>this</em>?',
    read: 'Read the treble staff, then tap its matching piano key.',
    answer: 'Tap your answer',
    almost: (n: Pitch) => <>Almost! You played <strong>{n}</strong>. Read the note and try again.</>,
    another: 'Try again',
    microphoneTitle: 'Listen to your real piano',
    microphoneIntro: 'The app compares the heard pitch with the note on screen and only advances when you play the correct one.',
    microphoneButton: 'Start microphone',
    microphoneStop: 'Stop microphone',
    microphoneWaiting: 'Waiting for microphone permission…',
    microphoneReady: 'The microphone is listening. Play the pitch on your piano.',
    microphoneIdle: 'Start the microphone and play the pitch close to the device.',
    microphoneUnsupported: 'This browser does not support microphone pitch detection.',
    microphoneDenied: 'Microphone permission was denied. Allow it and try again.',
    microphoneError: 'Could not start microphone listening right now.',
    microphoneCompleted: 'The microphone practice is complete.',
    target: (n: SongPitch) => `Play ${n} on your real piano`,
    detected: 'Heard pitch',
    detectedNone: 'No stable pitch yet',
    detectedCorrect: 'Correct pitch — moving on!',
    detectedWrong: 'Not the right pitch yet — try again.',
    completed: '🎉 You finished the whole microphone practice!',
    restartPractice: 'Restart practice',
    songIntro: 'Play the melody on your real piano. Start with the note shown on the staff.',
    songTarget: (n: SongPitch) => `Play the next note: ${n}`,
    songCompleted: (title: string) => `🎉 You played the whole ${title}!`,
    restartSong: 'Restart song',
    debug: 'Debug',
    debugEyebrow: 'DEBUG MODE · PITCH DETECTION',
    debugTitle: 'See how the app hears your pitch',
    debugLead: 'Play a note on your real piano near the microphone. There is nothing to complete — just a live look at what the app hears and why.',
    debugIntro: 'Start the microphone and play any key. The result updates continuously, note by note.',
    debugIdle: 'Start the microphone and play a note.',
    debugWaiting: 'Listening … play a note on the piano.',
    debugNote: 'Detected pitch',
    debugFrequencyLabel: 'Measured frequency',
    debugConfidenceLabel: 'Confidence',
    debugLevelLabel: 'Sound level (RMS)',
    debugReason: (label: string, hz: string, pct: number, rms: string) => `The app recognizes ${label} because the sound wave repeats in a pattern matching ${hz} Hz. A YIN-style periodicity analysis (CMNDF) found the best match with ${pct}% confidence, and the sound level (RMS ${rms}) was strong enough to trust the reading.`,
    debugUnstable: (hz: string, pct: number) => `Right now the signal is too weak or unclear for a confident pitch reading (frequency ${hz} Hz, only ${pct}% confidence).`,
    footer: <>Made for curious ears <span>·</span> No wrong notes here 🎵</>,
    version: (version: string) => `Version ${version}`,
    language: 'Language',
    swedish: 'Svenska',
    english: 'English',
    switchTo: (l: string) => `Switch language to ${l}`,
  },
} as const
